### ISSUE TITLE
Kicking out an adopted child says I have none, and they cannot move out themselves

### ISSUE THREAD

**Issue by cosmunn** [Janschuri/LunaticFamily#10]
**Running:**
- LunaticLib 1.1.11
- LunaticFamily 1.2.6
- Purpur 1.21-2257-cb0f04b (MC: 1.21)

**Description:**
After adopting a player, I cannot kick out and they cannot move out of the family. Trying to kick out says I have no child and them trying to move out generates an exception when confirming, pasted below. Listing the family successfully shows that we are in a family together.

**Image of the issue:**
![image](https://github.com/user-attachments/assets/97add9cc-5cee-49aa-9a47-c7f97438a0bc)
```
/adopt propose <player> | interacted on accept
confirms adoption       | confirms adoption
/adopt kickout <player> | -
-                       | /adopt moveout
-                       | interacted on confirm (exception)
/family list            | /family list
```

**Exception when moving out:**
```
Command exception: /family adopt moveout confirm
org.bukkit.command.CommandException: Unhandled exception executing command 'family' in plugin LunaticFamily v1.2.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2226) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2200) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1576) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1553) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1546) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1505) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1512) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1357) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
        at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
        at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at LunaticFamily-1.2.6.jar/de.janschuri.lunaticfamily.common.commands.adopt.AdoptMoveout.execute(AdoptMoveout.java:135) ~[LunaticFamily-1.2.6.jar:?]
        at LunaticFamily-1.2.6.jar/de.janschuri.lunaticfamily.common.commands.adopt.Adopt.execute(Adopt.java:71) ~[LunaticFamily-1.2.6.jar:?]
        at LunaticFamily-1.2.6.jar/de.janschuri.lunaticfamily.common.commands.family.Family.execute(Family.java:66) ~[LunaticFamily-1.2.6.jar:?]
        at LunaticLib-1.1.11.jar/de.janschuri.lunaticlib.platform.bukkit.commands.Command.onCommand(Command.java:25) ~[LunaticLib-1.1.11.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        ... 27 more
```

**Comment by Janschuri** [comment]
Hi! Thanks for your report! I fixed this in v1.2.7 I have uploaded a minute ago. Have a nice Day! #11
