### ISSUE TITLE
Families are no longer loading

### ISSUE THREAD

**Issue by cosmunn** [Janschuri/LunaticFamily#18]
**Running:**
- LunaticLib 1.2.0
- LunaticFamily 1.2.12
- Purpur 1.21-2279-9e444c5 (MC: 1.21)

**Description:**
After the 1.2.12 update, the plugin seems to not be able to find a player's relation in the database. 
I tried resetting the database and I could get into a relationship with another player, however as soon as the server restarts the problem shows up.

**Stack trace on player join:**
```
Could not pass event PlayerJoinEvent to LunaticFamily v1.2.12
java.lang.StackOverflowError: null
        at java.base/java.lang.StackStreamFactory$StackFrameTraverser.tryAdvance(StackStreamFactory.java:647) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.lambda$callerClassLoader$1(AbstractDefaultRulesReflectionProxy.java:62) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at java.base/java.lang.StackStreamFactory$StackFrameTraverser.consumeFrames(StackStreamFactory.java:586) ~[?:?]
        at java.base/java.lang.StackStreamFactory$AbstractStackWalker.doStackWalk(StackStreamFactory.java:324) ~[?:?]
        at java.base/java.lang.StackStreamFactory$AbstractStackWalker.callStackWalk(Native Method) ~[?:?]
        at java.base/java.lang.StackStreamFactory$AbstractStackWalker.beginStackWalk(StackStreamFactory.java:410) ~[?:?]
        at java.base/java.lang.StackStreamFactory$AbstractStackWalker.walkHelper(StackStreamFactory.java:261) ~[?:?]
        at java.base/java.lang.StackStreamFactory$AbstractStackWalker.walk(StackStreamFactory.java:253) ~[?:?]
        at java.base/java.lang.StackWalker.walk(StackWalker.java:589) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.callerClassLoader(AbstractDefaultRulesReflectionProxy.java:62) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at LunaticLib-1.2.0.jar/de.janschuri.lunaticlib.common.database.SQLite.getSQLConnection(SQLite.java:103) ~[LunaticLib-1.2.0.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.database.tables.PlayerDataTable.getSQLConnection(PlayerDataTable.java:39) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.database.tables.PlayerDataTable.getID(PlayerDataTable.java:47) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.<init>(FamilyPlayerImpl.java:51) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.<init>(FamilyPlayerImpl.java:38) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.getPartner(FamilyPlayerImpl.java:181) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.loadFamilyMap(FamilyPlayerImpl.java:421) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.update(FamilyPlayerImpl.java:110) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.<init>(FamilyPlayerImpl.java:61) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.<init>(FamilyPlayerImpl.java:38) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.getPartner(FamilyPlayerImpl.java:181) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.loadFamilyMap(FamilyPlayerImpl.java:421) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.update(FamilyPlayerImpl.java:110) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.<init>(FamilyPlayerImpl.java:61) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.<init>(FamilyPlayerImpl.java:38) ~[LunaticFamily-1.2.12.jar:?]
```
**When checking for family:** 
```
Command exception: /family list
org.bukkit.command.CommandException: Unhandled exception executing command 'family' in plugin LunaticFamily v1.2.12
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2226) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2200) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1354) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.StackOverflowError
        at java.base/java.util.stream.AbstractPipeline.wrapSink(AbstractPipeline.java:547) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.lambda$callerClassLoader$1(AbstractDefaultRulesReflectionProxy.java:62) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at java.base/java.lang.StackStreamFactory$StackFrameTraverser.consumeFrames(StackStreamFactory.java:586) ~[?:?]
        at java.base/java.lang.StackStreamFactory$AbstractStackWalker.doStackWalk(StackStreamFactory.java:324) ~[?:?]
        at java.base/java.lang.StackStreamFactory$AbstractStackWalker.callStackWalk(Native Method) ~[?:?]
        at java.base/java.lang.StackStreamFactory$AbstractStackWalker.beginStackWalk(StackStreamFactory.java:410) ~[?:?]
        at java.base/java.lang.StackStreamFactory$AbstractStackWalker.walkHelper(StackStreamFactory.java:261) ~[?:?]
        at java.base/java.lang.StackStreamFactory$AbstractStackWalker.walk(StackStreamFactory.java:253) ~[?:?]
        at java.base/java.lang.StackWalker.walk(StackWalker.java:589) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.callerClassLoader(AbstractDefaultRulesReflectionProxy.java:62) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[purpur-1.21.jar:1.21-2279-9e444c5]
        at LunaticLib-1.2.0.jar/de.janschuri.lunaticlib.common.database.SQLite.getSQLConnection(SQLite.java:103) ~[LunaticLib-1.2.0.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.database.tables.PlayerDataTable.getSQLConnection(PlayerDataTable.java:39) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.database.tables.PlayerDataTable.getUUID(PlayerDataTable.java:79) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.<init>(FamilyPlayerImpl.java:39) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.getPartner(FamilyPlayerImpl.java:181) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.loadFamilyMap(FamilyPlayerImpl.java:421) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.update(FamilyPlayerImpl.java:110) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.<init>(FamilyPlayerImpl.java:61) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.<init>(FamilyPlayerImpl.java:38) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.getPartner(FamilyPlayerImpl.java:181) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.loadFamilyMap(FamilyPlayerImpl.java:421) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.update(FamilyPlayerImpl.java:110) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.<init>(FamilyPlayerImpl.java:61) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.<init>(FamilyPlayerImpl.java:38) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.getPartner(FamilyPlayerImpl.java:181) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.loadFamilyMap(FamilyPlayerImpl.java:421) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.update(FamilyPlayerImpl.java:110) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.<init>(FamilyPlayerImpl.java:61) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.<init>(FamilyPlayerImpl.java:38) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.getPartner(FamilyPlayerImpl.java:181) ~[LunaticFamily-1.2.12.jar:?]
        at LunaticFamily-1.2.12.jar/de.janschuri.lunaticfamily.common.handler.FamilyPlayerImpl.loadFamilyMap(FamilyPlayerImpl.java:421) ~[LunaticFamily-1.2.12.jar:?]
```
(I've cut those a little because it just keeps repeating the same pattern at the bottom of the exception)

**Comment by cosmunn** [comment]
Saw that 1.2.13 released just minutes after I opened the issue, and it seems to be fixed! Thank you very much.

**Comment by Janschuri** [comment]
Hi! Thanks for reporting this issue. Yesterday, I accidentally uploaded a version where it starts looping while updating the players' relationships. I have removed that version and replaced it with a newer one. Please install the newer version and let me know if the error persists.
